/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package se;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 * root
 *
 * @author ashraf
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    functions ob = new functions();
    DefaultTableModel model_students;
    DefaultTableModel model_history;

    public gui() {
        initComponents();
        setSize(1230, 690);
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);


        model_students = (DefaultTableModel) jTable_students.getModel();
        model_history = (DefaultTableModel) jTable_history.getModel();



        jPanel_main.setSize(1230, 690);
        jPanel11.setBackground(new Color(0, 0, 0, 150));
        jPanel_insert.setSize(1230, 690);
        jPanel_insert.setBackground(new Color(0, 0, 0, 200));
        jPanel_search.setBackground(new Color(0, 0, 0, 200));
        jButton_add_insert.setBackground(new Color(0, 0, 0, 200));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_login = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel_main = new javax.swing.JPanel();
        jButton_search = new javax.swing.JButton();
        jButton_insert = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel_insert = new javax.swing.JPanel();
        jTextField_department = new javax.swing.JTextField();
        jTextField_name_student = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_no_section = new javax.swing.JTextField();
        jButton_add_insert = new javax.swing.JButton();
        jTextField_is_team = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_id_student = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton_back_insert = new javax.swing.JButton();
        jPanel_search = new javax.swing.JPanel();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTable_students = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jTextField_is_team_his = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_name_his = new javax.swing.JTextField();
        jCheckBox_id = new javax.swing.JCheckBox();
        jCheckBox_name = new javax.swing.JCheckBox();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTable_history = new javax.swing.JTable();
        jTextField_degree = new javax.swing.JTextField();
        jTextField_reson = new javax.swing.JTextField();
        jLabel_reason_Add = new javax.swing.JLabel();
        jLabel_degree_Add = new javax.swing.JLabel();
        jButton_add_insert1 = new javax.swing.JButton();
        jButton_back_insert1 = new javax.swing.JButton();
        jCheckBox_prime = new javax.swing.JCheckBox();
        jTextField_date_his = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel_name_update = new javax.swing.JLabel();
        jTextField_name_student_updatea = new javax.swing.JTextField();
        jTextField_no_section_updatea = new javax.swing.JTextField();
        jLabel_no_update = new javax.swing.JLabel();
        jTextField_department_updatea = new javax.swing.JTextField();
        jLabel_dept_update = new javax.swing.JLabel();
        jButton_update_student = new javax.swing.JButton();
        jLabel_degree_update = new javax.swing.JLabel();
        jLabel_date_update = new javax.swing.JLabel();
        jButton_update_his = new javax.swing.JButton();
        jTextField_degree_update = new javax.swing.JTextField();
        jTextField_reason_update = new javax.swing.JTextField();
        jLabel_reason_update = new javax.swing.JLabel();
        jTextField_date_update = new javax.swing.JTextField();
        jButton_delete_student = new javax.swing.JButton();
        jButton_delete_his = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel_login.setLayout(null);

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("LOGIN");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("password");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("use name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .addComponent(jPasswordField1)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addGap(0, 55, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addGap(11, 11, 11)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addGap(1, 1, 1)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        jPanel_login.add(jPanel11);
        jPanel11.setBounds(470, 190, 280, 310);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/ashtt.jpg.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(3000, 1500));
        jPanel_login.add(jLabel1);
        jLabel1.setBounds(-10, 0, 1230, 660);

        getContentPane().add(jPanel_login, "card3");

        jPanel_main.setLayout(null);

        jButton_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/index.png"))); // NOI18N
        jButton_search.setText("jButton1");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_search);
        jButton_search.setBounds(620, 290, 250, 160);

        jButton_insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/images.jpg"))); // NOI18N
        jButton_insert.setText("jButton1");
        jButton_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_insertActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_insert);
        jButton_insert.setBounds(880, 290, 250, 160);

        jButton_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/666.jpg"))); // NOI18N
        jButton_delete.setText("jButton1");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_delete);
        jButton_delete.setBounds(100, 290, 250, 160);

        jButton_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/update-icon1.png"))); // NOI18N
        jButton_update.setText("jButton1");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });
        jPanel_main.add(jButton_update);
        jButton_update.setBounds(360, 290, 250, 160);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/se/photos/ashtt.jpg.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(3000, 1500));
        jPanel_main.add(jLabel3);
        jLabel3.setBounds(-10, 0, 1230, 660);

        getContentPane().add(jPanel_main, "card3");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("depatment");

        jButton_add_insert.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_insert.setText("add");
        jButton_add_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_insertActionPerformed(evt);
            }
        });

        jTextField_is_team.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_is_teamActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("name student");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("no section");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("id student");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("id team");

        jButton_back_insert.setBackground(new java.awt.Color(0, 0, 0));
        jButton_back_insert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_back_insert.setForeground(new java.awt.Color(255, 255, 255));
        jButton_back_insert.setText("back");
        jButton_back_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_back_insertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_insertLayout = new javax.swing.GroupLayout(jPanel_insert);
        jPanel_insert.setLayout(jPanel_insertLayout);
        jPanel_insertLayout.setHorizontalGroup(
            jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_insertLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_insertLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_insertLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_id_student, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_is_team, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_no_section, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_name_student, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_department, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_add_insert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_back_insert, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel_insertLayout.setVerticalGroup(
            jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_insertLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_insertLayout.createSequentialGroup()
                        .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name_student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_department, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_is_team, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel_insertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id_student, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_no_section, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel_insertLayout.createSequentialGroup()
                        .addComponent(jButton_add_insert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_back_insert)))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_insert, "card4");

        jTable_students.setBackground(new java.awt.Color(0, 0, 0));
        jTable_students.setForeground(new java.awt.Color(255, 255, 255));
        jTable_students.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id team", "id student", "name student", "no section", "department", "total degrees"
            }
        ));
        jTable_students.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable_studentsMouseReleased(evt);
            }
        });
        jScrollPane27.setViewportView(jTable_students);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("id team");

        jTextField_is_team_his.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_is_team_hisKeyReleased(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("name student");

        jTextField_name_his.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_name_hisKeyReleased(evt);
            }
        });

        jCheckBox_id.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox_id.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_id.setText("search with id team ");
        jCheckBox_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_idActionPerformed(evt);
            }
        });

        jCheckBox_name.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox_name.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_name.setText("search with  id team and id student");
        jCheckBox_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_nameActionPerformed(evt);
            }
        });

        jTable_history.setBackground(new java.awt.Color(0, 0, 0));
        jTable_history.setForeground(new java.awt.Color(255, 255, 255));
        jTable_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id team", "id student", "degree", "reason", "date"
            }
        ));
        jTable_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable_historyMouseReleased(evt);
            }
        });
        jScrollPane28.setViewportView(jTable_history);

        jTextField_degree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_degreeActionPerformed(evt);
            }
        });

        jTextField_reson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_resonActionPerformed(evt);
            }
        });

        jLabel_reason_Add.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_reason_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_reason_Add.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_reason_Add.setText("reason");

        jLabel_degree_Add.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_degree_Add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_degree_Add.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_degree_Add.setText("degree");

        jButton_add_insert1.setBackground(new java.awt.Color(0, 0, 0));
        jButton_add_insert1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_add_insert1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_add_insert1.setText("add");
        jButton_add_insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add_insert1ActionPerformed(evt);
            }
        });

        jButton_back_insert1.setBackground(new java.awt.Color(0, 0, 0));
        jButton_back_insert1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_back_insert1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_back_insert1.setText("back");
        jButton_back_insert1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_back_insert1ActionPerformed(evt);
            }
        });

        jCheckBox_prime.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox_prime.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox_prime.setText("search with  id team and id student and date");
        jCheckBox_prime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_primeActionPerformed(evt);
            }
        });

        jTextField_date_his.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_date_hisKeyReleased(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("date");

        jLabel_name_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_name_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_name_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_name_update.setText("name student");

        jTextField_name_student_updatea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_name_student_updateaKeyReleased(evt);
            }
        });

        jTextField_no_section_updatea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_no_section_updateaKeyReleased(evt);
            }
        });

        jLabel_no_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_no_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_no_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_no_update.setText("no section");

        jTextField_department_updatea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_department_updateaKeyReleased(evt);
            }
        });

        jLabel_dept_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_dept_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_dept_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dept_update.setText("department");

        jButton_update_student.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update_student.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update_student.setText("update");
        jButton_update_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_studentActionPerformed(evt);
            }
        });

        jLabel_degree_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_degree_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_degree_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_degree_update.setText("degree");

        jLabel_date_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_date_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_date_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_date_update.setText("date");

        jButton_update_his.setBackground(new java.awt.Color(0, 0, 0));
        jButton_update_his.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_update_his.setForeground(new java.awt.Color(255, 255, 255));
        jButton_update_his.setText("update");
        jButton_update_his.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_update_hisActionPerformed(evt);
            }
        });

        jTextField_degree_update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_degree_updateKeyReleased(evt);
            }
        });

        jTextField_reason_update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_reason_updateKeyReleased(evt);
            }
        });

        jLabel_reason_update.setBackground(new java.awt.Color(0, 0, 0));
        jLabel_reason_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_reason_update.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_reason_update.setText("reason");

        jTextField_date_update.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_date_updateKeyReleased(evt);
            }
        });

        jButton_delete_student.setBackground(new java.awt.Color(0, 0, 0));
        jButton_delete_student.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delete_student.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete_student.setText("delete");
        jButton_delete_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_studentActionPerformed(evt);
            }
        });

        jButton_delete_his.setBackground(new java.awt.Color(0, 0, 0));
        jButton_delete_his.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_delete_his.setForeground(new java.awt.Color(255, 255, 255));
        jButton_delete_his.setText("delete");
        jButton_delete_his.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_delete_hisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_searchLayout = new javax.swing.GroupLayout(jPanel_search);
        jPanel_search.setLayout(jPanel_searchLayout);
        jPanel_searchLayout.setHorizontalGroup(
            jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_searchLayout.createSequentialGroup()
                        .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_searchLayout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jCheckBox_id)
                                .addGap(26, 26, 26)
                                .addComponent(jCheckBox_name)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_date_his, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jCheckBox_prime)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_delete_his, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel_searchLayout.createSequentialGroup()
                        .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 1121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_searchLayout.createSequentialGroup()
                                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_searchLayout.createSequentialGroup()
                                        .addComponent(jLabel_name_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_name_student_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel_no_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_no_section_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel_dept_update)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_department_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_searchLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel_searchLayout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_is_team_his, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_name_his, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel_searchLayout.createSequentialGroup()
                                                .addComponent(jLabel_degree_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel_reason_Add)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextField_reson, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(99, 99, 99)
                                        .addComponent(jButton_add_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_searchLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton_delete_student, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel_searchLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton_back_insert1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton_update_student, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap(84, Short.MAX_VALUE))))
            .addGroup(jPanel_searchLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel_degree_update)
                .addGap(18, 18, 18)
                .addComponent(jTextField_degree_update, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel_reason_update)
                .addGap(12, 12, 12)
                .addComponent(jTextField_reason_update, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel_date_update)
                .addGap(18, 18, 18)
                .addComponent(jTextField_date_update, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton_update_his, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_searchLayout.setVerticalGroup(
            jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_searchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_degree, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_reason_Add)
                    .addComponent(jLabel_degree_Add)
                    .addComponent(jTextField_reson, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_add_insert1)
                    .addComponent(jButton_back_insert1))
                .addGap(27, 27, 27)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_name_student_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_name_update)
                    .addComponent(jTextField_no_section_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_no_update)
                    .addComponent(jTextField_department_updatea, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_dept_update)
                    .addComponent(jButton_update_student))
                .addGap(35, 35, 35)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_is_team_his, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jTextField_name_his, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_delete_student))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_degree_update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_reason_update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_reason_update)
                    .addComponent(jTextField_date_update, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_date_update)
                    .addComponent(jButton_update_his)
                    .addComponent(jLabel_degree_update))
                .addGap(30, 30, 30)
                .addGroup(jPanel_searchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_id)
                    .addComponent(jCheckBox_name)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_date_his, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_prime)
                    .addComponent(jButton_delete_his))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_search, "card5");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            ob.conn(jTextField2.getText(), jPasswordField1.getText());
            jPanel_login.setVisible(false);
            jPanel_main.setVisible(true);

        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "error \n check your user name and password");
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error \n check your user name and password");
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }





    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // TODO add your handling code here:
        jPanel_main.setVisible(false);
        jPanel_search.setVisible(true);

        jTextField_degree.setVisible(true);
        jTextField_reson.setVisible(true);
        jButton_add_insert1.setVisible(true);
        
       
        
        jTextField_name_student_updatea.setVisible(false);
        jTextField_department_updatea.setVisible(false);
        jTextField_no_section_updatea.setVisible(false);
        jButton_update_student.setVisible(false);
        jTextField_date_update.setVisible(false);
        jTextField_degree_update.setVisible(false);
        jTextField_reason_update.setVisible(false);
        jButton_update_his.setVisible(false);
         
        jLabel_degree_Add.setVisible(true);
        jLabel_reason_Add.setVisible(true);
        jLabel_name_update.setVisible(false);
        jLabel_dept_update.setVisible(false);
        jLabel_no_update.setVisible(false);
        jLabel_date_update.setVisible(false);
        jLabel_degree_update.setVisible(false);
        
        jLabel_reason_update.setVisible(false);
        jButton_delete_student.setVisible(false);
        jButton_delete_his.setVisible(false);
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_insertActionPerformed
        // TODO add your handling code here:
        jPanel_main.setVisible(false);
        jPanel_insert.setVisible(true);
    }//GEN-LAST:event_jButton_insertActionPerformed

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        jPanel_main.setVisible(false);
        jPanel_search.setVisible(true);

        jTextField_degree.setVisible(false);
        jTextField_reson.setVisible(false);
        jButton_add_insert1.setVisible(false);

        jTextField_name_student_updatea.setVisible(false);
        jTextField_department_updatea.setVisible(false);
        jTextField_no_section_updatea.setVisible(false);
        jButton_update_student.setVisible(false);
        jTextField_date_update.setVisible(false);
        jTextField_degree_update.setVisible(false);
        jTextField_reason_update.setVisible(false);
        jButton_update_his.setVisible(false);

        
        jLabel_degree_Add.setVisible(false);
        jLabel_reason_Add.setVisible(false);
        jLabel_name_update.setVisible(false);
        jLabel_dept_update.setVisible(false);
        jLabel_no_update.setVisible(false);
        jLabel_date_update.setVisible(false);
        jLabel_degree_update.setVisible(false);
        
        jLabel_reason_update.setVisible(false);

        jButton_delete_student.setVisible(true);
        jButton_delete_his.setVisible(true);
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        jPanel_main.setVisible(false);
        jPanel_search.setVisible(true);

        jLabel_degree_Add.setVisible(false);
        jLabel_reason_Add.setVisible(false);
        jLabel_name_update.setVisible(true);
        jLabel_dept_update.setVisible(true);
        jLabel_no_update.setVisible(true);
        jLabel_date_update.setVisible(true);
        jLabel_degree_update.setVisible(true);
        
        jLabel_reason_update.setVisible(true);
        
        
        jTextField_degree.setVisible(false);
        jTextField_reson.setVisible(false);
        jButton_add_insert1.setVisible(false);

        jTextField_name_student_updatea.setVisible(true);
        jTextField_department_updatea.setVisible(true);
        jTextField_no_section_updatea.setVisible(true);
        jButton_update_student.setVisible(true);
        jTextField_date_update.setVisible(true);
        jTextField_degree_update.setVisible(true);
        jTextField_reason_update.setVisible(true);
        jButton_update_his.setVisible(true);


        jButton_delete_student.setVisible(false);
        jButton_delete_his.setVisible(false);
    }//GEN-LAST:event_jButton_updateActionPerformed

private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton_add_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_insertActionPerformed
        // TODO add your handling code here:

        String id_team = jTextField_is_team.getText();
        String id_student = jTextField_id_student.getText();
        String name = jTextField_name_student.getText();
        String no = jTextField_no_section.getText();
        String dept = jTextField_department.getText();
        boolean flag_no = ob.check_int(no);
        if (flag_no == false) {
            jTextField_no_section.setBackground(Color.pink);
        }
        boolean flag = true;

        ResultSet rs = ob.search_student_id_team_students(id_team, id_student);
        try {
            rs.next();


            if (rs.getString("id_team").length() != 0) {
                flag = false;
                JOptionPane.showMessageDialog(null, "sorry there is a student that has id =" + id_student + " in team =" + id_team);
                jTextField_id_student.setBackground(Color.pink);
                jTextField_is_team.setBackground(Color.pink);
            }
        } catch (Exception e) {
        }

        if (flag == true && flag_no == true) {
            ob.insert_students(id_team, id_student, name, no, dept);
            jTextField_id_student.setText("");
            jTextField_is_team.setText("");
            jTextField_name_student.setText("");
            jTextField_id_student.setBackground(Color.white);
            jTextField_is_team.setBackground(Color.white);
            jTextField_no_section.setBackground(Color.white);
            JOptionPane.showMessageDialog(null, "sucessful operation");
        }




    }//GEN-LAST:event_jButton_add_insertActionPerformed

    private void jButton_back_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_back_insertActionPerformed
        // TODO add your handling code here:
        jPanel_main.setVisible(true);
        jPanel_insert.setVisible(false);
    }//GEN-LAST:event_jButton_back_insertActionPerformed

    private void jTable_studentsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_studentsMouseReleased
        // TODO add your handling code here:

        int x = jTable_students.getSelectedRow();
        String id_team = (String) model_students.getValueAt(x, 0);
        String id_student = (String) model_students.getValueAt(x, 1);
        String n = (String) model_students.getValueAt(x, 2);
        String noo = (String) model_students.getValueAt(x, 3);
        String de = (String) model_students.getValueAt(x, 4);
        jTextField_department_updatea.setText(de);
        jTextField_no_section_updatea.setText(noo);
        jTextField_name_student_updatea.setText(n);

        model_history.setRowCount(0);
        if (jCheckBox_id.isSelected()) {
            ResultSet rs = ob.search_history_id_team(id_team);
            try {
                while (rs.next()) {
                    String degree = rs.getString("degree");
                    String reason = rs.getString("reason");
                    String date = rs.getString("date");
                    model_history.addRow(new Object[]{id_team, id_student, degree, reason, date});
                }
            } catch (SQLException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jCheckBox_name.isSelected()) {
            ResultSet rs = ob.search_history_id_team_student(id_team, id_student);
            try {
                while (rs.next()) {
                    String degree = rs.getString("degree");
                    String reason = rs.getString("reason");
                    String date = rs.getString("date");
                    model_history.addRow(new Object[]{id_team, id_student, degree, reason, date});
                }
            } catch (SQLException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            String date = jTextField_date_his.getText();
            ResultSet rs = ob.search_history_primary(id_team, id_student, date);
            try {
                while (rs.next()) {
                    String degree = rs.getString("degree");
                    String reason = rs.getString("reason");

                    model_history.addRow(new Object[]{id_team, id_student, degree, reason, date});
                }
            } catch (SQLException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jTable_studentsMouseReleased

    private void jTextField_is_teamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_is_teamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_is_teamActionPerformed

    private void jTable_historyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_historyMouseReleased
        // TODO add your handling code here:
        int x = jTable_history.getSelectedRow();
        String degree = (String) model_history.getValueAt(x, 2);
        String res = (String) model_history.getValueAt(x, 3);
        String date = (String) model_history.getValueAt(x, 4);
        jTextField_degree_update.setText(degree);
        jTextField_reason_update.setText(res);
        jTextField_date_update.setText(date);
    }//GEN-LAST:event_jTable_historyMouseReleased

    private void jTextField_degreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_degreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_degreeActionPerformed

    private void jTextField_resonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_resonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_resonActionPerformed

    private void jButton_add_insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add_insert1ActionPerformed
        // TODO add your handling code here:
        int x = jTable_students.getSelectedRow();
        String id_team = "";
        try {
            id_team = (String) model_students.getValueAt(x, 0);
        } catch (Exception e) {
        }
        if (id_team.length() != 0) {
            String id_student = (String) model_students.getValueAt(x, 1);
            String total_degree = (String) model_students.getValueAt(x, 5);

            String degree = jTextField_degree.getText();
            String reson = jTextField_reson.getText();
            boolean flag_deg = ob.check_int(degree);
            if (flag_deg == false) {
                jTextField_degree.setBackground(Color.pink);
            }
            boolean flag_primary = true;
            ResultSet rs = ob.search_history_primary(id_team, id_student, ob.time_now());
            try {
                rs.next();
                if (rs.getString("id_team").length() != 0) {
                    flag_primary = false;
                    JOptionPane.showMessageDialog(null, "this student have been taken degree in this day before");
                }
            } catch (Exception e) {
            }
            if (flag_deg == true && flag_primary == true) {
                ob.insert_history(id_team, id_student, degree, reson);
                ob.update_total_degree_students(id_team, id_student, total_degree, degree);

                jTextField_degree.setBackground(Color.white);
                JOptionPane.showMessageDialog(null, "sucessful operation");
            }

        } else {
            JOptionPane.showMessageDialog(null, "please choose a student from table students then try again ");
        }
    }//GEN-LAST:event_jButton_add_insert1ActionPerformed

    private void jButton_back_insert1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_back_insert1ActionPerformed
        jPanel_search.setVisible(false);
        jPanel_main.setVisible(true);
    }//GEN-LAST:event_jButton_back_insert1ActionPerformed

    private void jCheckBox_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_idActionPerformed
        // TODO add your handling code here:
        jCheckBox_name.setSelected(false);
        jCheckBox_prime.setSelected(false);

    }//GEN-LAST:event_jCheckBox_idActionPerformed

    private void jCheckBox_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_nameActionPerformed
        // TODO add your handling code here:
        jCheckBox_id.setSelected(false);

        jCheckBox_prime.setSelected(false);
    }//GEN-LAST:event_jCheckBox_nameActionPerformed

    private void jTextField_is_team_hisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_is_team_hisKeyReleased
        // TODO add your handling code here:
        model_students.setRowCount(0);
        String id_team = jTextField_is_team_his.getText();
        ResultSet rs = ob.search_student_id_team(id_team);
        try {
            while (rs.next()) {
                String id_student = rs.getString("id_student");
                String name_student = rs.getString("name_student");
                String no = rs.getString("num_sec");
                String dept = rs.getString("dept");
                String total_degree = rs.getString("total_degress");
                model_students.addRow(new Object[]{id_team, id_student, name_student, no, dept, total_degree});
            }
        } catch (SQLException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jTextField_is_team_hisKeyReleased

    private void jTextField_name_hisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_name_hisKeyReleased
        // TODO add your handling code here:
        model_students.setRowCount(0);
        String name = jTextField_name_his.getText();
        ResultSet rs = ob.search_student_name(name);
        try {
            while (rs.next()) {
                String id_team = rs.getString("id_team");
                String id_student = rs.getString("id_student");
                String name_student = rs.getString("name_student");
                String no = rs.getString("num_sec");
                String dept = rs.getString("dept");
                String total_degree = rs.getString("total_degress");
                model_students.addRow(new Object[]{id_team, id_student, name_student, no, dept, total_degree});
            }
        } catch (SQLException ex) {
            Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField_name_hisKeyReleased

    private void jCheckBox_primeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_primeActionPerformed
        // TODO add your handling code here:
        jCheckBox_id.setSelected(false);

        jCheckBox_name.setSelected(false);
    }//GEN-LAST:event_jCheckBox_primeActionPerformed

    private void jTextField_date_hisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_date_hisKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_date_hisKeyReleased

    private void jTextField_name_student_updateaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_name_student_updateaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_name_student_updateaKeyReleased

    private void jTextField_no_section_updateaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_no_section_updateaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_no_section_updateaKeyReleased

    private void jTextField_department_updateaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_department_updateaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_department_updateaKeyReleased

    private void jButton_update_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_studentActionPerformed
        // TODO add your handling code here:
        int x = jTable_students.getSelectedRow();
        if (x > -1) {
            String name = jTextField_name_student_updatea.getText();
            String no = jTextField_no_section_updatea.getText();
            String department = jTextField_department_updatea.getText();
            boolean flag = ob.check_int(no);
            if (flag == false) {
                jTextField_no_section_updatea.setBackground(Color.pink);
            } else {
                String id_team = (String) model_students.getValueAt(x, 0);
                String id_stu = (String) model_students.getValueAt(x, 1);


                try {
                    System.out.println("update students set name_student='" + name + "' and num_sec=" + no + " and dept='" + department + "' where id_team='"
                            + id_team + "' and id_student='" + id_stu + "'");
                    ob.stmt.executeUpdate("update students set name_student='" + name + "' , num_sec=" + no + " , dept='" + department + "' where id_team='"
                            + id_team + "' and id_student='" + id_stu + "'");

                    JOptionPane.showMessageDialog(null, "sucessful operation");

                } catch (SQLException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton_update_studentActionPerformed

    private void jButton_update_hisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_update_hisActionPerformed
        // TODO add your handling code here:
        int x = jTable_history.getSelectedRow();
        if (x > -1) {
            String degree = jTextField_degree_update.getText();
            String res = jTextField_reason_update.getText();
            String date = jTextField_date_update.getText();
            boolean flag_deg = ob.check_int(degree);
            if (flag_deg == false) {
                jTextField_degree_update.setBackground(Color.pink);
            }

            boolean flag_date = true;
            try {
                flag_date = ob.check_time(date, 1);
            } catch (ParseException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (flag_date == false) {
                jTextField_date_update.setBackground(Color.pink);
            }


            if (flag_date == true && flag_deg == true) {
                String id_team = (String) model_history.getValueAt(x, 0);
                String id_stu = (String) model_history.getValueAt(x, 1);
                String deg = (String) model_history.getValueAt(x, 2);


                try {
                    ob.stmt.executeUpdate("update history set degree=" + degree + " , reason='" + res + "' , date='" + date + "' where id_team='"
                            + id_team + "' and id_student='" + id_stu + "'");
                    ResultSet rs = ob.search_student_id_team_students(id_team, id_stu);
                    rs.next();

                    String old_de = rs.getString("total_degress");
                    if (Double.parseDouble(deg) > Double.parseDouble(degree)) {
                           ob.update_total_degree_students(id_team, id_stu, old_de,
                                String.valueOf((Double.parseDouble(deg)-Double.parseDouble(degree))*-1)) ; 
                    // ob.update_total_degree_students(id_team, id_stu, old_de, String.valueOf(Double.parseDouble(degree) * -1));
                    }
                    else 
                    {
                       ob.update_total_degree_students(id_team, id_stu, old_de,
                                String.valueOf((Double.parseDouble(degree)-Double.parseDouble(deg)))) ; 
                    }
                   


                    JOptionPane.showMessageDialog(null, "sucessful operation");
                } catch (SQLException ex) {
                    Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton_update_hisActionPerformed

    private void jTextField_degree_updateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_degree_updateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_degree_updateKeyReleased

    private void jTextField_reason_updateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_reason_updateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_reason_updateKeyReleased

    private void jTextField_date_updateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_date_updateKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_date_updateKeyReleased

    private void jButton_delete_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_studentActionPerformed
        // TODO add your handling code here:

        int x = jTable_students.getSelectedRow();
        if (x > -1) {
            String id_team = (String) model_students.getValueAt(x, 0);
            String id_stu = (String) model_students.getValueAt(x, 1);
            try {
                int o = JOptionPane.showConfirmDialog(null, "are you sure ?");
                if (o == 0) {
                    ob.stmt.executeUpdate("delete from students where id_team='" + id_team + "' and id_student='" + id_stu + "'");
                    ob.stmt.executeUpdate("delete from history where id_team='" + id_team + "' and id_student='" + id_stu + "'");
                    model_students.removeRow(x);
                    model_history.setRowCount(0);
                 JOptionPane.showMessageDialog(null,"successful operation" );
                }


            } catch (SQLException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_jButton_delete_studentActionPerformed

    private void jButton_delete_hisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_delete_hisActionPerformed
        // TODO add your handling code here:
        int x = jTable_history.getSelectedRow();
        if (x > -1) {
            String id_team = (String) model_history.getValueAt(x, 0);
            String id_stu = (String) model_history.getValueAt(x, 1);
            String date = (String) model_history.getValueAt(x, 4);
            String degree = (String) model_history.getValueAt(x, 2);
            try {
                int o = JOptionPane.showConfirmDialog(null, "are you sure ?");
                if (o == 0) {
                    ob.stmt.executeUpdate("delete from history where id_team='" + id_team + " and id_student='" + id_stu + "' and date='" + date + "'");
                    ResultSet rs = ob.search_student_id_team_students(id_team, id_stu);
                    rs.next();
                    String old_de = rs.getString("total_degress");
                    
                   
                   
                    ob.update_total_degree_students(id_team, id_stu, old_de, String.valueOf(Double.parseDouble(degree) * -1));
                    
                    model_history.removeRow(x);
                    JOptionPane.showMessageDialog(null, "successful operation");
                }


            } catch (SQLException ex) {
                Logger.getLogger(gui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton_delete_hisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new gui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton_add_insert;
    private javax.swing.JButton jButton_add_insert1;
    private javax.swing.JButton jButton_back_insert;
    private javax.swing.JButton jButton_back_insert1;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_delete_his;
    private javax.swing.JButton jButton_delete_student;
    private javax.swing.JButton jButton_insert;
    private javax.swing.JButton jButton_search;
    private javax.swing.JButton jButton_update;
    private javax.swing.JButton jButton_update_his;
    private javax.swing.JButton jButton_update_student;
    private javax.swing.JCheckBox jCheckBox_id;
    private javax.swing.JCheckBox jCheckBox_name;
    private javax.swing.JCheckBox jCheckBox_prime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_date_update;
    private javax.swing.JLabel jLabel_degree_Add;
    private javax.swing.JLabel jLabel_degree_update;
    private javax.swing.JLabel jLabel_dept_update;
    private javax.swing.JLabel jLabel_name_update;
    private javax.swing.JLabel jLabel_no_update;
    private javax.swing.JLabel jLabel_reason_Add;
    private javax.swing.JLabel jLabel_reason_update;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel_insert;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPanel jPanel_search;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JTable jTable_history;
    private javax.swing.JTable jTable_students;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField_date_his;
    private javax.swing.JTextField jTextField_date_update;
    private javax.swing.JTextField jTextField_degree;
    private javax.swing.JTextField jTextField_degree_update;
    private javax.swing.JTextField jTextField_department;
    private javax.swing.JTextField jTextField_department_updatea;
    private javax.swing.JTextField jTextField_id_student;
    private javax.swing.JTextField jTextField_is_team;
    private javax.swing.JTextField jTextField_is_team_his;
    private javax.swing.JTextField jTextField_name_his;
    private javax.swing.JTextField jTextField_name_student;
    private javax.swing.JTextField jTextField_name_student_updatea;
    private javax.swing.JTextField jTextField_no_section;
    private javax.swing.JTextField jTextField_no_section_updatea;
    private javax.swing.JTextField jTextField_reason_update;
    private javax.swing.JTextField jTextField_reson;
    // End of variables declaration//GEN-END:variables
}
